# 配置文件

DAILY_TIME: "07：15" # 每日定时发送时间。该时间为系统时间，如果当前系统时间不为北京时间需要自行进行换算

START_DATE: "2022-09-26" # 纪念日
CITY: "郑州"

BIRTHDAY:
  - "06-01"

APP_ID: "wx59c3d5db11fb6205"
APP_SECRET: "155aa30595703ed5e528eb1afe41aba9"

USER_ID: 
  - "o2iBz6vd_JNfXDegGBKOwR2UM4-M"
TEMPLATE_ID: "2diprDTPQcM5ybEZmGji5WcmWb5_4Tk_vNEjwH6VvtE"
